# Generated by Django 5.2 on 2025-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_status',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=200),
        ),
    ]
