# Generated by Django 5.2 on 2025-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UGX.', 'UGX.'), ('USD.', 'USD.'), ('EUR.', 'EUR.'), ('KSH.', 'KSH.')], default='UGX.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='--Select--', max_length=200),
        ),
    ]
