# Generated by Django 5.2 on 2025-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0005_product_currency_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
