# Generated by Django 5.2 on 2025-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0007_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
