# Generated by Django 5.2 on 2025-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0008_remove_order_shipping_address_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(auto_created=True, unique=True),
        ),
    ]
