# Generated by Django 5.2 on 2025-04-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.PositiveIntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='Units',
            field=models.CharField(choices=[('--select--', '--select--'), ('pieces', 'pieces'), ('kgs', 'kgs'), ('tins', 'tins'), ('bags', 'bags'), ('trucks', 'trucks'), ('litres', 'litres')], default='--Select--', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
