# Generated by Django 5.2 on 2025-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0010_remove_order_total_amount_order_quantity_order_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Units',
            field=models.CharField(choices=[('--select--', '--select--'), ('cars', 'cars'), ('pieces', 'pieces'), ('kgs', 'kgs'), ('tins', 'tins'), ('bags', 'bags'), ('trucks', 'trucks'), ('litres', 'litres')], default='--Select--', max_length=200),
        ),
    ]
