# Generated by Django 5.2 on 2025-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0012_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.PositiveIntegerField(auto_created=True),
        ),
    ]
