# Generated by Django 5.2 on 2025-04-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0016_alter_accountsettings_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettings',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='accountsettings',
            old_name='contact_email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='accountsettings',
            old_name='contact_phone',
            new_name='company_phone',
        ),
    ]
