# Generated by Django 5.2 on 2025-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierre_CMS_App', '0017_rename_address_accountsettings_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='company_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
